name: Build Firefox (Cross Platform)
on:
  push:
    branches:
      - master
jobs:
  build_mac_intel:
    name: MacOSX (Intel) - Build Firefox
    runs-on: macos-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - name: Set up Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - name: "Set up Python" 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: "Brew Install Mercurial"
        run: brew install mercurial
      - name: "Brew Install git-cinnabar"
        run: brew install git-cinnabar
      - name: Import Keychain Certs
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: "Pulling correct Firefox and extension sources"
        run: ./fern.js use
      - name: "Applying patches to Firefox"
        run: ./fern.js import-patches
      - name: "Overwriting mach to new version"
        working-directory: mozilla-release
        run: cp $GITHUB_WORKSPACE/build/mach .
      - name: "Bootstraping Firefox build environment"
        working-directory: mozilla-release
        run: printf "1\nY\n" | ./mach bootstrap
      - name: "Building Firefox from source (./mach build)"
        working-directory: mozilla-release
        run: MOZCONFIG=$GITHUB_WORKSPACE/brands/impervious/mozconfig ./mach build
      - name: "Packaging the Firefox build for distribution"
        working-directory: mozilla-release
        run: ./mach package
      # - name: "Signing the Firefox package"
      #   run: sh ci/sign_mac.sh
      # - name: "Looking for the build artifact"
      #   run: ls -la dist/Impervious
      - name: "Upload artifacts to Job"
        uses: actions/upload-artifact@v3
        with:
          name: Impervious MacOSX x86_64
          #working-directory: mozilla-release
          path: /Users/runner/work/imp-browser-staging/**/Impervious*.dmg

          
  # build_mac_aarch64:
  #   name: MacOSX (M1) - Build Firefox
  #   runs-on: macos-latest
  #   steps:
  #     - name: Check Out Code
  #       uses: actions/checkout@v2
  #     - name: Set up Node Environment
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16"
  #     - run: npm ci
  #     - name: "Set up Python" 
  #       uses: actions/setup-python@v3
  #       with:
  #         python-version: '3.9' 
  #     - name: Set Up Rust
  #       run: |
  #         rustup target add aarch64-apple-darwin
  #     - name: Import Keychain Certs
  #       uses: apple-actions/import-codesign-certs@v1
  #       with: 
  #         p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
  #         p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
  #     - name: "Pulling correct Firefox and extension sources"
  #       run: ./fern.js use
  #     - name: "Applying patches to Firefox"
  #       run: ./fern.js import-patches
  #     - name: "Bootstraping Firefox build environment"
  #       working-directory: mozilla-release
  #       run: printf "1\nY\n" | ./mach bootstrap
  #     - name: "Building Firefox from source (./mach build)"
  #       working-directory: mozilla-release
  #       run: MOZCONFIG=$GITHUB_WORKSPACE/brands/impervious/mozconfig-aarch64-apple-darwin ./mach build
  #     - name: "Packaging the Firefox build for distribution"
  #       working-directory: mozilla-release
  #       run: ./mach package
  #     - name: "Signing the Firefox package"
  #       run: sh ci/sign_mac.sh
  #     - name: "Looking for the build artifact"
  #       run: ls -la dist/Impervious
  #     - name: "Upload artifacts to Job"
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: Impervious MacOSX aarch64 (M1)
  #         path: dist/Impervious/*
  # build_linux:
  #   name: Linux - Build Firefox
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "apt-get update"
  #       run: sudo apt-get update
  #     - name: "apt-get install -y apt-transport-https"
  #       run: sudo apt-get install -y apt-transport-https
  #     - name: Check Out Code
  #       uses: actions/checkout@v2
  #     - name: Set up Node Environment
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "16"
  #     - run: npm ci
  #     - name: "Pulling correct Firefox and extension sources"
  #       run: ./fern.js use
  #     - name: "Applying patches to Firefox"
  #       run: ./fern.js import-patches
  #     - name: "Bootstraping Firefox build environment"
  #       working-directory: ./mozilla-release
  #       run: printf "1\nY\n" | ./mach bootstrap
  #     - name: "Building Firefox from source (./mach build)"
  #       working-directory: ./mozilla-release
  #       run: MOZCONFIG=$GITHUB_WORKSPACE/brands/impervious/mozconfig ./mach build
  #     - name: "Looking for the build artifact"
  #       working-directory: ./mozilla-release
  #       run: ls
